export const carData = [
  // Automatic Cars
  {
    id: 1,
    name: "Hyundai",
    model: "Creta",
    type: "Automatic",
    rating: 4.6,
    passengers: 5,
    transmission: "Automatic",
    price: "15.61L",
    range: "600 km",
    battery: "50 kWh",
    power: "115 bhp",
    charging: "7 hrs",
    bodyStyle: "SUV",
    warranty: "5 yr/1,00,000 km",
    length: "4300 mm",
    width: "1790 mm",
    height: "1635 mm",
    weight: "1500 kg",
    cargoVolume: "400 L",
    about: "The Hyundai Creta is a stylish and reliable compact SUV, offering great performance and comfort. With its premium features and efficient fuel consumption, it's perfect for both city drives and long journeys.",
    image: "/images/hcreta.jpeg",
    priceRange: "₹ 13.5L - ₹ 17.5L",
    monthlyTestDriveFee: "₹ 5000",
    securityDeposit: "₹ 20,000",
    totalAmount: "₹ 15,81,000",
    freeKilometers: "1500 km",
    vendor: "Hyundai",
  },
  {
    id: 2,
    name: "Kia",
    model: "Seltos",
    type: "Automatic",
    rating: 4.7,
    passengers: 5,
    transmission: "Automatic",
    price: "14.65L",
    range: "650 km",
    battery: "55 kWh",
    power: "140 bhp",
    charging: "6.5 hrs",
    bodyStyle: "SUV",
    warranty: "5 yr/1,00,000 km",
    length: "4370 mm",
    width: "1800 mm",
    height: "1620 mm",
    weight: "1450 kg",
    cargoVolume: "433 L",
    about: "The Kia Seltos is a bold and powerful SUV designed for adventure. It combines advanced technology, high fuel efficiency, and comfort to make every drive enjoyable.",
    image: "/images/kiaseltos.jpg",
    priceRange: "₹ 13.0L - ₹ 16.5L",
    monthlyTestDriveFee: "₹ 4500",
    securityDeposit: "₹ 18,000",
    totalAmount: "₹ 15,20,000",
    freeKilometers: "1600 km",
    vendor: "Kia",
  },
  {
    id: 3,
    name: "Toyota",
    model: "Fortuner",
    type: "Automatic",
    rating: 4.8,
    passengers: 7,
    transmission: "Automatic",
    price: "32.59L",
    range: "800 km",
    battery: "65 kWh",
    power: "170 bhp",
    charging: "8 hrs",
    bodyStyle: "SUV",
    warranty: "5 yr/1,00,000 km",
    length: "4795 mm",
    width: "1855 mm",
    height: "1835 mm",
    weight: "2500 kg",
    cargoVolume: "500 L",
    about: "The Toyota Fortuner is a high-performance, full-size SUV known for its rugged durability and off-road capabilities. Ideal for those seeking both luxury and adventure.",
    image: "/images/toyotafortuner.jpg",
    priceRange: "₹ 30.0L - ₹ 35.0L",
    monthlyTestDriveFee: "₹ 7000",
    securityDeposit: "₹ 30,000",
    totalAmount: "₹ 35,59,000",
    freeKilometers: "2000 km",
    vendor: "Toyota",
  },
  {
    id: 4,
    name: "Honda",
    model: "City",
    type: "Automatic",
    rating: 4.5,
    passengers: 5,
    transmission: "Automatic",
    price: "13.89L",
    range: "700 km",
    battery: "60 kWh",
    power: "120 bhp",
    charging: "7 hrs",
    bodyStyle: "Sedan",
    warranty: "3 yr/1,00,000 km",
    length: "4549 mm",
    width: "1748 mm",
    height: "1485 mm",
    weight: "1200 kg",
    cargoVolume: "510 L",
    about: "The Honda City is a sleek and comfortable sedan offering great fuel efficiency, advanced safety features, and an elegant design that makes it perfect for city drives.",
    image: "/images/hondacity.webp",
    priceRange: "₹ 13.0L - ₹ 15.5L",
    monthlyTestDriveFee: "₹ 4000",
    securityDeposit: "₹ 15,000",
    totalAmount: "₹ 14,89,000",
    freeKilometers: "1200 km",
    vendor: "Honda",
  },

  // Hybrid Cars
  {
    id: 5,
    name: "Toyota",
    model: "Camry",
    type: "Hybrid",
    rating: 4.8,
    passengers: 5,
    transmission: "Automatic",
    price: "41.70L",
    range: "900 km",
    battery: "80 kWh",
    power: "215 bhp",
    charging: "6 hrs",
    bodyStyle: "Sedan",
    warranty: "5 yr/1,00,000 km",
    length: "4850 mm",
    width: "1840 mm",
    height: "1450 mm",
    weight: "1700 kg",
    cargoVolume: "450 L",
    about: "The Toyota Camry Hybrid offers an excellent combination of luxury, efficiency, and performance. With its eco-friendly hybrid technology, it ensures lower emissions and better fuel economy.",
    image: "/images/Camry1-4.jpeg",
    priceRange: "₹ 40.0L - ₹ 45.0L",
    monthlyTestDriveFee: "₹ 8000",
    securityDeposit: "₹ 35,000",
    totalAmount: "₹ 45,70,000",
    freeKilometers: "1800 km",
    vendor: "Toyota",
  },
  {
    id: 6,
    name: "Honda",
    model: "CR-V Hybrid",
    type: "Hybrid",
    rating: 4.6,
    passengers: 5,
    transmission: "Automatic",
    price: "30.00L",
    range: "850 km",
    battery: "75 kWh",
    power: "190 bhp",
    charging: "7 hrs",
    bodyStyle: "SUV",
    warranty: "5 yr/1,00,000 km",
    length: "4600 mm",
    width: "1855 mm",
    height: "1680 mm",
    weight: "1600 kg",
    cargoVolume: "450 L",
    about: "The Honda CR-V Hybrid combines fuel efficiency with Honda’s signature comfort and reliability. It's a great choice for those looking for an eco-friendly yet powerful SUV.",
    image: "/images/crv.jpeg",
    priceRange: "₹ 28.0L - ₹ 32.0L",
    monthlyTestDriveFee: "₹ 6000",
    securityDeposit: "₹ 25,000",
    totalAmount: "₹ 32,00,000",
    freeKilometers: "1500 km",
    vendor: "Honda",
  },

  // Electric Cars
  {
    id: 7,
    name: "TATA",
    model: "Nexon EV",
    type: "Electric",
    rating: 4.8,
    passengers: 4,
    transmission: "Automatic",
    price: "12.49L",
    range: "312 km",
    battery: "30 kWh",
    power: "129 bhp",
    charging: "8 hrs",
    bodyStyle: "SUV",
    warranty: "8 yr/1,60,000 km",
    length: "3993 mm",
    width: "1811 mm",
    height: "1606 mm",
    weight: "1400 kg",
    cargoVolume: "350 L",
    about: "The TATA Nexon EV is an affordable electric SUV that combines great range, powerful performance, and eco-friendliness. It’s a perfect option for those looking to make the switch to electric.",
    image: "/images/nexon.jpeg",
    priceRange: "₹ 12.0L - ₹ 14.0L",
    monthlyTestDriveFee: "₹ 4000",
    securityDeposit: "₹ 15,000",
    totalAmount: "₹ 13,00,000",
    freeKilometers: "1200 km",
    vendor: "TATA",
  },
  {
    id: 8,
    name: "MG",
    model: "ZS EV",
    type: "Electric",
    rating: 4.7,
    passengers: 5,
    transmission: "Automatic",
    price: "23.38L",
    range: "400 km",
    battery: "44.5 kWh",
    power: "143 bhp",
    charging: "6 hrs",
    bodyStyle: "SUV",
    warranty: "5 yr/1,00,000 km",
    length: "4323 mm",
    width: "1809 mm",
    height: "1645 mm",
    weight: "1500 kg",
    cargoVolume: "470 L",
    about: "The MG ZS EV is a feature-packed electric SUV with a stylish design, advanced safety features, and an impressive range. It's perfect for those looking for an affordable yet high-performing electric vehicle.",
    image: "/images/zsev.webp",
    priceRange: "₹ 22.0L - ₹ 25.0L",
    monthlyTestDriveFee: "₹ 5000",
    securityDeposit: "₹ 20,000",
    totalAmount: "₹ 24,50,000",
    freeKilometers: "1500 km",
    vendor: "MG",
  },
  {
    id: 9,
    name: "Tesla",
    model: "Model 3",
    type: "Electric",
    rating: 4.9,
    passengers: 5,
    transmission: "Automatic",
    price: "60.00L",
    range: "560 km",
    battery: "82 kWh",
    power: "283 bhp",
    charging: "5 hrs",
    bodyStyle: "Sedan",
    warranty: "8 yr/1,60,000 km",
    length: "4694 mm",
    width: "1850 mm",
    height: "1440 mm",
    weight: "1800 kg",
    cargoVolume: "425 L",
    about: "The Tesla Model 3 is a revolutionary electric sedan known for its sleek design, exceptional range, and cutting-edge technology. It's a top choice for those seeking performance and sustainability.",
    image: "/images/model3.webp",
    priceRange: "₹ 58.0L - ₹ 62.0L",
    monthlyTestDriveFee: "₹ 9000",
    securityDeposit: "₹ 50,000",
    totalAmount: "₹ 62,00,000",
    freeKilometers: "2000 km",
    vendor: "Tesla",
  },
];
