export const carData = [
    {
        id: 1,
        name: "TATA",
        model: "Nexon EV",
        type: "Electric",
        rating: 4.8,
        passengers: 4,
        transmission: "Automatic",
        price: "12.49",
        range: "312",
        battery: "30",
        power: "129",
        charging: "8",
        bodyStyle: "SUV",
        warranty_years: 8,
        warranty_km: 160000,
        length: "3993",
        width: "1811",
        height: "1606",
        weight: "1400 kg",
        cargoVolume: "350",
        about: "The TATA Nexon EV is an affordable electric SUV that combines great range, powerful performance, and eco-friendliness. It’s a perfect option for those looking to make the switch to electric.",
        image: "/images/Cars/tnex.jpeg",
        priceRange: "₹ 12.0L - ₹ 14.0L",
        monthlyTestDriveFee: "4000",
        securityDeposit: "15,000",
        totalAmount: "13,00,0",
        freeKilometers: "1200",
        vendor: "TATA",
      },
]
