export const carData = [
    {
        id: 1,
        name: "TATA",
        model: "Nexon EV",
        type: "Electric",
        rating: 4.8,
        passengers: 4,
        transmission: "Automatic",
        price: "12.49L",
        range: "312 km",
        battery: "30 kWh",
        power: "129 bhp",
        charging: "8 hrs",
        bodyStyle: "SUV",
        warranty: "8 yr/1,60,000 km",
        length: "3993 mm",
        width: "1811 mm",
        height: "1606 mm",
        weight: "1400 kg",
        cargoVolume: "350 L",
        about: "The TATA Nexon EV is an affordable electric SUV that combines great range, powerful performance, and eco-friendliness. It’s a perfect option for those looking to make the switch to electric.",
        image: "/images/Cars/tnex.jpeg",
        priceRange: "₹ 12.0L - ₹ 14.0L",
        monthlyTestDriveFee: "₹ 4000",
        securityDeposit: "₹ 15,000",
        totalAmount: "₹ 13,00,000",
        freeKilometers: "1200 km",
        vendor: "TATA",
      },
]
